### ISSUE TITLE
Could madmax defect reentrance or other famous vulnerability?

### ISSUE THREAD

**Issue by ouerum** [nevillegrech/MadMax#3]
Hi, I have used your famous Ethereum smart contract vulnerability detect tool, Madmax. I find only 3 vulnerability about DOS can be detected. 
Could madmax defect other bug? I can't find the souffle file about other bug except `oldclient.dl`. But the result from this souffle file is not well, more than 50% was flagged with reentrance, the false positive may be too high. 
Another word, I am interesting in your related work, gigahorse. The result of gigahorse from contract-lib is lower than 50% in detecting reentrancy, have you change to use another souffle file to detect, or the same file `oldclient.dl`?

**Comment by nevillegrech** [comment]
Hi the reentrancy implementation in contract-library.com has nothing to do with oldclient.dl and uses Gigahorse, not Vandal. MadMax only detects gas-related vulnerabilities, although the techniques developed have inspired later work such as Gigahorse.

**Comment by ouerum** [comment]
Thanks for your respond. Have you published the datalog file of the implementation in contract-library.com in github?

**Comment by nevillegrech** [comment]
No we haven't yet

**Comment by ouerum** [comment]
Well, I am looking forward your related work about smart contract analysis. The job of madmax and gigahorse is prefect!

**Comment by nevillegrech** [comment]
Hi ouerum, it should now be relatively straightforward to implement your client (or other clients) using the underlying framework.

https://github.com/nevillegrech/gigahorse-toolchain

**Comment by ouerum** [comment]
Got it, I have forked gigahorse a week ago, thank a lot for your notifications. Gigahorse has helped my analysis project for smart contracts. 😃



在 2020年12月27日，上午4:38，Neville Grech <notifications@github.com> 写道：

﻿

Closed #3<https://github.com/nevillegrech/MadMax/issues/3>.

**Comment by ouerum** [comment]
Hello, I have a question after reading your paper 'Elipmoc: Advanced Decompilation of Ethereum Smart Contracts’.
I have clone the Gigahorse project from Github in Dec 2020(0be6260f), is it the code of Elipmoc (gigahorse 2.0) or the original Gigahorse?

Thanks a lot for your reply.
在 2020年12月27日 +0800 10:15，何 嘉浩 ***@***.***>，写道：
