### ISSUE TITLE
How to get the graphs of the paper.

### ISSUE THREAD

**Issue by crx934080895** [nevillegrech/MadMax#4]
I see these graph in your paper. Can I generate these graph by this repository's code or other way？
Look forward to your reply.
![QQ截图20201111191748](https://user-images.githubusercontent.com/44501441/98805586-c8388e80-2452-11eb-8a92-d1eb4658b868.png)
![QQ截图20201111191756](https://user-images.githubusercontent.com/44501441/98805592-ca025200-2452-11eb-8280-4faee590364e.png)

**Comment by nevillegrech** [comment]
The graphing code is not part of the repo. I used matplotlib's venn3, on the processed dataset derived from the output relations. Here's a code snippet I found (for the lower-left diagram):

```
subscript_iter = list(product('01', '01', '01'))[1:]
sets = [len(results[(results.InStructuredLoop == int(a)) & (results.ArrayIdToStorageIndex == int(b)) & (results.PossibleArrayIterator == int(c))]) for a,b,c in subscript_iter]
sets_size = [1, 1, 1, 1, 1, 1, 3]

v=venn3(subsets = sets_size, set_labels = ('Has Loops', 'Has Arrays', 'Has Array Iterators'))
c=venn3_circles(subsets = sets_size, linestyle = 'dotted')
c[2].set_lw(1.0)
c[2].set_ls('solid')
for label, subscript in zip(sets, subscript_iter):
    #patch = v.get_label_by_id("{0:03b}".format(7-i))
    patch = v.get_label_by_id(''.join(subscript))
    if patch:
        patch.set_text(label if label else '')

#plt.title("Insights",fontsize=30)

plt.show()
```

**Comment by crx934080895** [comment]
Thanks for your reply.
It 's my fault to express my question by mistake.
I mean, how to get the data of these graphs rather than generating these graphs.
I want to analysis my contracts to generate the graphs like above.

**Comment by crx934080895** [comment]
Thanks for your reply.
It 's my fault to express my question by mistake.
I mean, how to get the data of these graphs rather than generating these graphs.
I want to analysis my contracts to generate the graphs likes above.

**Comment by nevillegrech** [comment]
The data will be in results.json, if you use the bulk analyzer.

**Comment by nevillegrech** [comment]
We updated instructions
